title: 听松阁美图
author: 听松阁
email: kylehao@mail.com
description: >-
  听松阁美图，清纯，唯美.

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
